### ISSUE TITLE
Possible GC-related bugfix

### ISSUE THREAD

**Issue by timholy** [JuliaGtk/Gtk4.jl#11]
Not sure if it's relevant here (I haven't even looked), but worth mentioning that https://github.com/JuliaGraphics/Gtk.jl/pull/682 fixes a subtle and previously-undiscovered bug.

**Comment by tknopp** [comment]
I could not find `MutableX{T}` in the code but @jwahlstrand knows better.

**Comment by jwahlstrand** [comment]
All the `Mutable` stuff was replaced with `Ref`, so hopefully Gtk4 is immune to that. But I'll look into it further before closing this. Thanks for bringing it up!
