### ISSUE TITLE
Document dialogs

### ISSUE THREAD

**Issue by tknopp** [JuliaGtk/Gtk4.jl#14]
The dialogs are currently not documented. This is just a reminder for us to do so. We need to document the synchronous and asynchronous variants and give clear examples like the one in https://github.com/JuliaGtk/Gtk4.jl/pull/13 how to call dialogs from callbacks.

In addition to the high-level methods we should also showcase how to write a custom dialog with `GtkDialog`.

**Comment by jwahlstrand** [comment]
I have part of this done locally (along with other unfinished docs). I'll update it and commit.

**Comment by jwahlstrand** [comment]
I just added a bit more to the documentation on dialogs. Regarding `GtkDialog`, it was deprecated in GTK 4.10 (see https://blog.gtk.org/2022/10/30/on-deprecations/) in favor of just creating a `GtkWindow` (as is done in `input_dialog` now). I added an example of that.

I'm going to close this but as always feel free to reopen.
