### ISSUE TITLE
Regressions to Gtk.jl

### ISSUE THREAD

**Issue by tknopp** [JuliaGtk/Gtk4.jl#15]
The purpose of this issue is to track regressions compared to Gtk.jl, which will help us to find a good moment for migration of packages.

### Mac
- [x] Windows are popping up in the lower right corner (fixed by GTK4_jll 4.6.9)
- [ ] Windows are opened in the background
- [x] I have sometimes segfaults when resizing the window (fixed by GTK4_jll 4.6.9)

**Comment by jwahlstrand** [comment]
# Windows

- [ ] Fullscreen doesn't work
- [ ] Pressing buttons inside dialogs doesn't work

**Comment by jwahlstrand** [comment]
GTK4_jll 4.6.9 is now available. I'm finding that on my Mac, windows are no longer in the lower right corner. They still open behind the Julia terminal but in front of other windows. I haven't seen the segfault issue myself.

**Comment by tknopp** [comment]
So the only regression I see is that the Windows on Mac are not opened on top. In my opinion this should not be a show-stopper for the Gtk4 migration. Thought's?

I would like to change Winston.jl very soon to Gtk4, which we can probably use as a first test since it has almost no users. Another idea is then to integrate Gtk4.jl with CairoMakie.jl, see https://github.com/MakieOrg/Makie.jl/issues/568#issuecomment-1364508362

**Comment by tknopp** [comment]
I think we want both, CairoMakie and GLMakie integration. How to properly put this into packages is unclear to me. Package extensions will likely change how we structure packages. In this particular case having a "Gtk4" package extension in CairoMakie.jl seems to be a good solution. But this is only theoretical. I have no experience so far.

**Comment by tknopp** [comment]
> Go for it, if someone wants to use Winston with Gtk.jl they can always pin the Winston version, right?

yep, exactly. I will make a major version bump.

**Comment by tknopp** [comment]
Winston migration done: https://github.com/JuliaRegistries/General/pull/75168 :-)
