### ISSUE TITLE
Container Iteration

### ISSUE THREAD

**Issue by tknopp** [JuliaGtk/Gtk4.jl#19]
In Gtk.jl one could iterate over containers using
```julia
for iter in container
  ...
end
```
This is because of this code:
https://github.com/JuliaGraphics/Gtk.jl/blob/881fdce8eb5a8bce2f1a846f79ac7142177e5b2a/src/container.jl#L41
It got removed in Gtk4.jl since `GtkContainer` has been removed.
I could replicate it using
```julia
iter = G_.get_first_child(container)
while iter != nothing
  ....
  iter = G_.get_next_sibling(iter)
end
```
Question is whether we should implement the iteration protocol for `GtkWidgets` or if we stick to the above code. In any case we should document/test it (hence this issue).

**Comment by jwahlstrand** [comment]
Iteration Julia style is implemented for GtkWidget:

https://github.com/JuliaGtk/Gtk4.jl/blob/8da6f6a68a1903f77342b3b0b6af0b99327b59fb/src/base.jl#L154-L160

And it's in the documentation:

https://github.com/JuliaGtk/Gtk4.jl/blob/8da6f6a68a1903f77342b3b0b6af0b99327b59fb/docs/src/manual/layout.md?plain=1#L119-L126

It's definitely possible that it's not implemented properly. I  haven't used it a lot myself but I did just check that this works:

```
using Gtk4

w=GtkWindow("iteration")
b=GtkBox(:v)
push!(b,GtkLabel("first"))
push!(b,GtkLabel("second"))
push!(b,GtkLabel("third"))
push!(b,GtkLabel("fourth"))
push!(b,GtkLabel("fifth"))

for l in b
  println(l.label)
end
```

**Comment by tknopp** [comment]
Oh, I yesterday got an error and thought it was therefore not implemented. Will check this later and close this issue if I got something wrong.

**Comment by tknopp** [comment]
Ok, I mixed this up with `getindex` and `length`, which are both missing and would also be handy. Closing this one.

**Comment by jwahlstrand** [comment]
Right, I don't think there are methods in the library corresponding to those, so they will have to involve iteration.
