### ISSUE TITLE
Multiple Selection mode example incorrect?

### ISSUE THREAD

**Issue by bilderbuchi** [JuliaGtk/Gtk4.jl#20]
In https://github.com/JuliaGtk/Gtk4.jl/blob/232cbe0d3516f5c54c1b636d310f77c5c0e3f4d0/docs/src/manual/listtreeview.md?plain=1#L112, the docs say to get multiple selection, do 
```
selection = Gtk4.mode(selection,Gtk4.SelectionMode_MULTIPLE)
```
However, I realised that with this, `selection` becomes nothing. Instead, as seen in [the tests](https://github.com/JuliaGtk/Gtk4.jl/blob/232cbe0d3516f5c54c1b636d310f77c5c0e3f4d0/test/gui.jl#L714), `selection` seems to be modified in place. When I use it like that, my code seems to work correctly.

It looks to me like the docs should be adapted.

**Comment by jwahlstrand** [comment]
This is fixed now, thanks!
