### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jwahlstrand** [JuliaGtk/Gtk4.jl#3]
I'd like to set up hosting for the documentation in /docs, which was mostly adapted from Gtk.jl. It looks like I don't have sufficient permissions to do so on this repo.

@tknopp, can you help?

**Comment by jwahlstrand** [comment]
Fixed -- we can link to the docs on juliahub.

**Comment by tknopp** [comment]
Sorry that I did not see this. Made you an owner of JuliaGtk.

**Comment by jwahlstrand** [comment]
No problem, thanks!
