### ISSUE TITLE
Migrate GTK4_jll to 4.10

### ISSUE THREAD

**Issue by Clemapfel** [JuliaGtk/Gtk4.jl#31]
Hi, I know it's only been out a few months but are there plans to migrate [GTK4_jll](https://github.com/JuliaBinaryWrappers/GTK4_jll.jl) to 4.10 soon? 4.10 deprecated a lot of things like `FileChooserDialog` and `TreeView`, as well as introducing a number of central new features like `FileDialog` which cannot be reproduced with just 4.8. It would be nice to be able to rely on all GTK4 Julia users having these available.

These 4.10 features do not need to be implemented in GTK4.jl yet, I am only asking for the binary builder package to be updated, as it would be nice to be able to depend on them when using GTK4_jll as a dependency, which something I am working on does.

Afaik it would only be upping the version variable [here](https://github.com/JuliaPackaging/Yggdrasil/blob/9221ae9c14c12fa14a5079a50f91a68dd9e41eaf/G/GTK4/build_tarballs.jl#L6).

Thank you

**Comment by jwahlstrand** [comment]
Yes, I had planned to do this and just submitted a PR: https://github.com/JuliaPackaging/Yggdrasil/pull/6938. It's unfortunately not usually just a matter of upping the version...

**Comment by tknopp** [comment]
Any reason to not go even further and migrate to 4.11.4 or is that a dev release.
I am currently struggling with this issue:
  https://discourse.gnome.org/t/menu-button-gives-error-messages-with-latest-gtk4/15689
Not sure if that is fixed in 4.11.4 but in 4.10.5 it is supposed to be fixed (could not find information if that is out yet)

**Comment by jwahlstrand** [comment]
I've been annoyed by those errors too. 4.11.4 is a dev release, but I'll update to 4.10.5 as soon as it's released.
