### ISSUE TITLE
GtkLabel markup can't display characters

### ISSUE THREAD

**Issue by Rratic** [JuliaGtk/Gtk4.jl#32]
```jl
label = GtkLabel("")
Gtk4.markup(label, """<span size="x-large">A</span>""")
```

`A` displays as a small box with four hex digits

environment:
```jl
julia> versioninfo()
Julia Version 1.9.1
Commit 147bdf428c (2023-06-07 08:27 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores

(@v1.9) pkg> st Gtk4
Status `C:\Users\anonymous\.julia\environments\v1.9\Project.toml`
  [9db2cae5] Gtk4 v0.4.1
```

**Comment by jwahlstrand** [comment]
It works correctly for me on Linux, but I also see the boxes on Windows. Seems likely to be an upstream issue -- I'll try updating Pango_jll.

**Comment by jwahlstrand** [comment]
Updating HarfBuzz_jll, a dependency of Pango_jll and GTK4_jll, fixes this. There is a PR: https://github.com/JuliaPackaging/Yggdrasil/pull/8392

Until that goes through (and a few other PR's that will be necessary to allow that version of HarfBuzz to be used by other JLL's), here is a way to use updated JLL's:

```
using Pkg

Pkg.add(url="https://github.com/jwahlstrand/libass_jll.jl")
Pkg.add(url="https://github.com/jwahlstrand/Pango_jll.jl")
Pkg.add(url="https://github.com/jwahlstrand/HarfBuzz_jll.jl")
```

**Comment by jwahlstrand** [comment]
Fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/8392
