### ISSUE TITLE
Using ThreadPool :interactive for the Gtk loop

### ISSUE THREAD

**Issue by nHackel** [JuliaGtk/Gtk4.jl#47]
Hello! I've been wondering if there have been any attempts to get the GTK loop running in a task scheduled on the [interactive](https://docs.julialang.org/en/v1/manual/multi-threading/#man-threadpools) pool if available.

A while ago I made a quick attempt at just scheduling the `glib_main` in the interactive pool but things crashed. I'd be willing to try again with some pointers

**Comment by jwahlstrand** [comment]
I did look into this a bit and (at least in 1.9) the GTK loop runs in the interactive pool, if it exists, without any extra setup.

This code, whether run in the REPL or as a script, for me prints "interactive" when there's an interactive thread pool. The `@idle_add` macro calls a function from the main loop so it's an easy way to check this.

```
using Gtk4

@idle_add println(Threads.threadpool())
if !isinteractive()
    Gtk4.GLib.start_main_loop()
    sleep(0.1) # allow println to be called before the loop is stopped
end
```

I haven't yet tried to use this in a real program where both threadpools are used. I would guess that `@idle_add` may be more important, just to make sure that GTK functions are called in the right thread.
