### ISSUE TITLE
How to use menubar?

### ISSUE THREAD

**Issue by caijinyan18700965617** [JuliaGtk/Gtk4.jl#63]
I want to generate a UI based on Gtk4.jl, with a menubar that only includes a GtkMenuButton among the menu-related options. I couldn't find MenuBar. I could find GMenuModel and GMenuItem. However, they cannot be pushed to the any layoutObject. Could you add a tutorial about how to add a menubar?

**Comment by jwahlstrand** [comment]
For now you could look at Gtk4Makie for an example.

I do not see MenuBar in the GTK4 documentation. We only provide what's in GTK4.

**Comment by jwahlstrand** [comment]
Here's a bit of documentation, hope this helps: https://juliagtk.github.io/Gtk4.jl/dev/manual/menus/

There's also an example of defining a menu and menu button.
