### ISSUE TITLE
open_dialog warning

### ISSUE THREAD

**Issue by pvermees** [JuliaGtk/Gtk4.jl#71]
The following script was put together using code snippets from the documentation:

```
using Gtk4
win = GtkWindow("open_dialog tester", 400, 200)
function f(filename)
   println(filename * " loaded")
end
open_dialog(f, "Pick a file to open", win)
```

Running it from the REPL gives the following warning:

```
(process:259564): Gtk-WARNING **: 08:28:46.055: Attempting to add 'file:///home/test/test.txt' to the list of recently used resources, but no name of the application that is registering it was defined
```

I don't know if this is a bug or a feature, but how does one get rid of this warning?

**Comment by jwahlstrand** [comment]
What platform? This is something the underlying C library is doing. I will look for a way of quieting the warning this weekend.

**Comment by jwahlstrand** [comment]
The warning is being emitted because the application name isn't set: https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkrecentmanager.c?ref_type=heads#L932

Try the following before calling `open_dialog`:

```
Gtk4.GLib.G_.set_application_name("myapp")
Gtk4.GLib.G_.set_prgname("myapp")
```

For me that gets rid of the warning. Maybe these should be set to something like "julia" or "Gtk4.jl" by default in the package if `GtkApplication` is not used (which handles this automatically).

Let me know if this helps.

**Comment by pvermees** [comment]
Now I get
```
Gtk-WARNING **: 13:05:47.701: No IM module matching GTK_IM_MODULE=ibus found
```

**Comment by jwahlstrand** [comment]
Potential clue:

https://discourse.ubuntu.com/t/ibus-no-more-gtk-im-module-ibus/17727

I don't see that "ibus" warning, but I'm using GNOME on Fedora. From the discussion it sounds like GNOME sets up ibus automatically.

Could you set `ENV["GTK_IM_MODULE"]="ibus"`?

**Comment by pvermees** [comment]
I can't quite figure out how to do this. I will be offline for a couple of days but will investigate it further when I return.  You've already helped me a lot.  Thanks!

**Comment by jwahlstrand** [comment]
I was able to try this on GNOME on Ubuntu and the "ibus" warning doesn't appear. So it looks like a i3wm + Ubuntu issue? Thanks for pointing out the other warning, I had seen it but didn't realize it was easy to fix.

**Comment by pvermees** [comment]
All fine now. Thanks for the help!
